backend:
  name: github
  repo: adstr123/bi-replicate

media_folder: "src/images"
public_folder: "/images"

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: product
    label: Product
    folder: /static/products
    create: true
    fields:
      - { name: slug, label: URL Slug }
      - { name: title, label: Title }
      - { name: category, label: Category }
      - { name: body, label: Body, widget: markdown }